##  After learning so much in Numpy, It's time for an assignment. 

### You are a student and today is your Numpy test. The test will consist of 10 questions, purely related to code. You need to write code for the given questions.



#### Q-1 Import Numpy and Write the code to know the version of numpy you are working on ?
Your output should look like this. <br>
NOTE : Numpy version may be different for you.

In [57]:
import numpy as np

In [58]:
np.__version__

'1.23.5'

In [59]:
# import numpy as np
# print("Current Numpy version :", np.__version__)

#### Q - Create a numpy array having elements from 1 to 16 (inclusive) and print it.
Your output should look like this.

In [4]:
arr = np.arange(1, 17)

In [5]:
print (arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [6]:
# arr = np.arange(1, 17)
# print(arr)

#### Q-3 You need to filter the previous array in such a way that , it only contains odd values.
Note : You have to use boolean indexing.<br>
Your output should look like this.

In [7]:
 filter_array = arr[arr%2==1]

In [8]:
print(filter_array)

[ 1  3  5  7  9 11 13 15]


In [9]:
# filter_array = arr[arr%2==1]
# print(filter_array)

#### Q-4  Replace values that give remainder as 1 when divided by 2 from the above resulted array with 0
Your output should look like this.

In [10]:
print(filter_array)

[ 1  3  5  7  9 11 13 15]


In [11]:
 print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [12]:
# arr[arr%2==0] = 0
# print(arr)

#### Q-5  Change the shape of above resulted array to 4x4.
Your output should look like this.

In [13]:
arr = arr.reshape(4,4)

In [14]:
 print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [15]:
# arr = arr.reshape(4,4)
# print(arr)

#### Q-6 Stack the resulted array with itself vertically.
Your output should look like this.

In [16]:
new_arr = np.vstack((arr,arr))

In [17]:
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [18]:
# ew_arnr = np.vstack((arr,arr))
# print(new_arr)

#### Q-7 On this vertical stacked resulted array, reverse the column order in alternate manner. column new order = [ 2,1,4,3 ]
Your output should look like this.

In [19]:
new_arr =  new_arr[:, [1,0,3,2]]

In [20]:
print(new_arr)

[[ 2  1  4  3]
 [ 6  5  8  7]
 [10  9 12 11]
 [14 13 16 15]
 [ 2  1  4  3]
 [ 6  5  8  7]
 [10  9 12 11]
 [14 13 16 15]]


In [21]:
# new_arr =  new_arr[:, [1,0,3,2]]
# print(new_arr)

#### Q-8 Calculate , mean , median and mode of the resulting array.
Your output should look like this.

In [44]:
mean = np.mean(new_arr)
median = np.median(new_arr)



(_, idx, counts) = np.unique(new_arr.reshape(32,), return_index=True, return_counts=True)
index = idx[np.argmax(counts)]
mode = new_arr.reshape(32,)[index]

In [45]:
print("Mean :", mean)
print("Median :", median)
print("Mode :", mode)

Mean : 8.5
Median : 8.5
Mode : 1


In [46]:
print("Mean :", mean)

Mean : 8.5


In [47]:
print("Median :", median)

Median : 8.5


In [48]:
print("Mode :", mode)

Mode : 1


#### Q-9 Create an array of 5 values , that are selected at random from the above resulted array.
Your output should look like this.

In [49]:
 random_arr = np.array([np.random.choice(new_arr.reshape(32,)) for i in range(5)])

In [50]:
 print("Random Element Array :", random_arr)

Random Element Array : [10 11 14  6  2]


In [23]:
# random_arr = np.array([np.random.choice(new_arr.reshape(32,)) for i in range(5)])
# print("Random Element Array :", random_arr)

#### Q-10 Complete the function, that calculate the value of this function (a.k.a Binary Cross Entropy) using  Vectorization.
`Given -
    y  : a vector of N dimension,
    y^ : a vector of N dimension
    N : elements in y and y^
    Use : log base 2
    `

<img src="BCE.png" width=500>

Your output should look like this.

In [24]:
def BCE(y, y_hat):
    pass

In [25]:
y = np.array([0.13,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.1])
y_hat = np.array([0.2,0.3,0.4,0.3,0.6,0.8,0.7,0.5,0.8,0.1])

result = BCE(y, y_hat)
print(result)

None


In [54]:
# def BCE(y, y_hat):
# return ((y*np.log2(y_hat) - (1 - y)*np.log2(1-y_hat))).mean()